title: SmartScale | Smarter way to Scale
baseURL: /
params:
  base_font: nunito-sans
  palette: blue
  header:
    logo_img: images/purple-lettuce.svg
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: primary
      - label: Features
        url: /features
        style: secondary
      - label: Pricing
        url: /pricing
        style: secondary
      - url: /contact
        style: primary
        has_icon: false
        icon: envelope
        icon_position: right
        new_window: false
        no_follow: false
        type: action
        label: Contact
      - label: Sign Up
        url: /signup
        style: primary
    logo_img_alt: alt="SmartScale"
  footer:
    sections:
      - type: footer_text
        image_url: /
        image_alt: SmartScale footer logo
        content: >
          **SmartScale** is a modern, easy to use industrial Weighing Scale
          Software for Weighing, Report Generation, Track Sales and moreâ€¦
        image: images/purple-lettuce.svg
      - type: footer_nav
        title: Quick Links
        nav_links:
          - label: About Us
            url: /about
            style: link
          - label: Blog
            url: /blog
            style: link
          - label: Contact
            url: /contact
            style: link
      - type: footer_nav
        title: We are social!
        nav_links:
          - label: youtube
            style: link
            has_icon: true
            icon: youtube
            icon_position: left
            new_window: true
            no_follow: false
            type: action
            url: 'https://www.youtube.com'
          - label: Twitter
            url: 'https://twitter.com'
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
            new_window: true
            no_follow: false
            type: action
          - label: Facebook
            url: 'https://facebook.com'
            style: link
            has_icon: true
            icon: facebook
            icon_position: left
            new_window: true
            no_follow: false
            type: action
      - image_alt: lorem-ipsum
        image_url: lorem-ipsum
        title: Contact Info
        content: |
          *   Dhaka, Bangladesh

          *   \+8801571386167

          *   sales@smartscale.com.bd
        type: footer_text
    has_nav: true
    nav_links:
      - label: Terms of Service
        url: /terms-of-service
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    content: '&copy; SmartScale 2021. All rights reserved.'
    links: []
  domain: 'https://smartscale.com.bd'
  favicon: images/favicon.ico
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
