title: Azimuth
baseURL: /
params:
  base_font: nunito-sans
  palette: blue
  header:
    logo_img: images/logo.svg
    logo_img_alt: Logo_SmartScale
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Features
        url: /features
        style: link
      - label: Pricing
        url: /pricing
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
      - label: Sign Up
        url: /signup
        style: primary
  footer:
    sections:
      - type: footer_text
        image: images/logo-alt.svg
        image_url: /
        image_alt: Footer logo
        content: >
          SmartScale is a modern, easy to use industrial Weighing Scale Software
          for Weighing, Report Generation, Track Sales and moreâ€¦
      - type: footer_nav
        title: Company
        nav_links:
          - label: About Us
            url: /about
            style: link
          - label: Blog
            url: /blog
            style: link
          - label: Sign Up
            url: /signup
            style: link
          - label: Contact
            url: /contact
            style: link
      - type: footer_nav
        title: We are social!
        nav_links:
          - label: Facebook
            style: link
            has_icon: true
            icon: facebook
            icon_position: left
            new_window: false
            no_follow: false
            type: action
            url: www.facebook.com
          - label: Twitter
            url: www.twitter.com
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
            new_window: false
            no_follow: false
            type: action
          - label: Youtube
            url: www.youtube.com
            style: link
            has_icon: true
            icon: youtube
            icon_position: left
            new_window: false
            no_follow: false
            type: action
          - label: E
            url: '#'
            style: link
            has_icon: true
            icon: envelope
            icon_position: left
            new_window: false
            no_follow: false
            type: action
      - type: footer_form
        title: Subscribe
        content: Stay up to date with our latest developments.
        form_id: contactForm
        hide_labels: true
        form_fields:
          - input_type: email
            name: email
            label: Email
            default_value: Enter email address
            is_required: true
        submit_label: Subscribe
    has_nav: true
    nav_links:
      - label: Terms of Service
        url: /terms-of-service
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>
  domain: 'https://smartscalewithstackbit-78888.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
